// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://liailakjvzzpqtpbgfpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpYWlsYWtqdnp6cHF0cGJnZnBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjI1NzIsImV4cCI6MjA3MTg5ODU3Mn0.1Zt-u9n-fLaif7gdL-_bWk0KnP1gjP7bxsP2YSOmFhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});